### PR TITLE
CI: Add Ruby 3.2

### PR DESCRIPTION
**Pull request by arturoherrero**
## Description

Add Ruby 3.2 CI support.

### CODE REVIEW

**Comment by arturoherrero** [comment]
Hi @lfittl, I'm curious to know how far we are in bringing support for Ruby 3.2. I'm creating this to see if we have any CI failures. Thanks!

**Comment by arturoherrero** [comment]
It looks like we have to update the `google-protobuf` gem to fix the [job failure](https://github.com/pganalyze/pg_query/actions/runs/4860819520/jobs/8710644206).

> google-protobuf-3.21.12-x86_64-linux requires ruby version < 3.2.dev, >= 2.5,
> which is incompatible with the current version, 3.2.2

Related to https://github.com/protocolbuffers/protobuf/issues/11578 and https://github.com/protocolbuffers/protobuf/issues/11538.

**Comment by arturoherrero** [comment]
@lfittl I'm not sure if 12d0387 is enough 😉

**Comment by arturoherrero** [comment]
It works! On the other hand, we should drop support of Ruby 2.5 because it's incompatible with the gem update. See the new [job failure](https://github.com/pganalyze/pg_query/actions/runs/4881786322/jobs/8723954148).

> google-protobuf-3.22.3-x86_64-linux requires ruby version < 3.3.dev, >= 2.6,
> which is incompatible with the current version, 2.5.9

I think it's okay because Ruby 2.5 End-Of-Life was 2021-04-05 (2 years ago)

Reference: https://www.ruby-lang.org/en/downloads/branches/

**Comment by arturoherrero** [comment]
@lfittl please review my previous message and 284b977. This should be ready now.

**Comment by arturoherrero** [comment]
👋 @lfittl Friendly reminder about this. Thanks!

**Review by lfittl — APPROVED** [review]

**Pull request merged**
